### ISSUE TITLE
App Crashes when launched from .jar

### ISSUE THREAD

**Issue by StrongJoshua** [kotcrab/VisEditor#13]
This is the error I get when trying to launch my game from a runnable .jar file:
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationExce
ption: Error reading file: com/kotcrab/vis/ui/uiskin.json
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:97)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.<init>(Skin.java:74)
        at com.kotcrab.vis.ui.VisUI.load(VisUI.java:55)
        at com.kotcrab.vis.ui.VisUI.load(VisUI.java:50)
        at com.strongjoshua.reverseblade.ReverseBlade.create(ReverseBlade.java:2
8)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplic
ation.java:143)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplicati
on.java:120)
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: co
m/kotcrab/vis/ui/uiskin.json
        at com.badlogic.gdx.utils.Json.fromJson(Json.java:683)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:95)
        ... 6 more
Caused by: com.badlogic.gdx.utils.SerializationException: Error parsing file: co
m/kotcrab/vis/ui/uiskin.json
        at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:77)
        at com.badlogic.gdx.utils.Json.fromJson(Json.java:681)
        ... 7 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: com\kotcr
ab\vis\ui\uiskin.json (Classpath)
        at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:137)
        at com.badlogic.gdx.files.FileHandle.reader(FileHandle.java:164)
        at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:75)
        ... 8 more
```
That line is when I call: `VisUI.load();`
I have had this happen with [my own LibGdx addon](https://github.com/StrongJoshua/libgdx-inGameConsole).

The only way I was able to prevent my plugin from erroring was to load the skin that it uses from my game itself, rather than the dependency's project. Maybe you have more insight into how to fix this.

**Comment by kotcrab** [comment]
What build system? Gradle or Maven?
26 maj 2015 5:00 AM "StrongJoshua" <notifications@github.com> napisał(a):

**Comment by StrongJoshua** [comment]
LibGdx projects use Gradle, so that's what I'm using.

**Comment by kotcrab** [comment]
Can't reproduce on fresh project from GDX setup app, also tested with Maven and everything works fine. Probably there is something wrong with your build scripts.

**Comment by StrongJoshua** [comment]
Alright I'll have a look at them after school. Can you post your working build script?

**Comment by kotcrab** [comment]
https://gist.github.com/kotcrab/8a8d164305c9bee44d35

**Comment by StrongJoshua** [comment]
I checked my build.gradle over and even tried using a clean project, but both showed the error. Maybe the problem is how I am packaging my game. How are you doing it? I just use the Eclipse export function (which worked before I included VisUI).

**Comment by kotcrab** [comment]
You can't use Eclipse export when using Gradle. See https://github.com/libgdx/libgdx/wiki/Gradle-on-the-Commandline#packaging-for-the-desktop

**Comment by StrongJoshua** [comment]
This is what I had been following: https://github.com/libgdx/libgdx/wiki/Deploying-your-application#deploy-to-windowslinuxmac-os-x Why is this incorrect?

**Comment by kotcrab** [comment]
It's form old build system, before Gradle was used. That page you linked says: "Note: if using gradle you may prefer following the guidelines provided on this page." It says "prefer" but the new Eclipse project setup page only links to Gradle packaging: https://github.com/libgdx/libgdx/wiki/Gradle-and-Eclipse#packaging-your-project .  Looks like Eclipse can't package resources from libs jars for Gradle based projects.

**Comment by StrongJoshua** [comment]
To do this I would need gradle installed and have it in my PATH, correct? Or is there some built-in gradle command line in Eclipse?

**Comment by kotcrab** [comment]
No, all you need is already in your project directory. You can just run `gradlew desktop:dist` command from cmd/terminal.

**Comment by StrongJoshua** [comment]
Just as an aside, do you know what the highest java source compatibility I can use is?

**Comment by kotcrab** [comment]
Desktop only: 1.8
With android: the safe one is 1.6, you can use 1.7 but not all features are supported.
GWT and iOS: I don't know, 1.6 will definitely work

Please use #libgdx irc for such questions.

**Comment by StrongJoshua** [comment]
Alright, well thanks anyways :)
