### ISSUE TITLE
VisEditor crashes if you remove shader.vert

### ISSUE THREAD

**Issue by intrigus** [kotcrab/VisEditor#21]
If you either remove shader.vert (what you normally shouldn't do) or paste shader.vert (into assets\shader) it crashes, because it tries to access shader.frag, without checking if shader.frag exists.

```
com.badlogic.gdx.utils.GdxRuntimeException: Error reading file: C:\Users\Simon\Downloads\visTest\vis\assets\shader\font (2).frag (Absolute)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:144)
	at com.badlogic.gdx.files.FileHandle.readString(FileHandle.java:202)
	at com.badlogic.gdx.files.FileHandle.readString(FileHandle.java:191)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.<init>(ShaderProgram.java:165)
	at com.kotcrab.vis.editor.module.project.ShaderCacheModule.reloadShaders(ShaderCacheModule.java:101)
	at com.kotcrab.vis.editor.module.project.ShaderCacheModule.access$1(ShaderCacheModule.java:60)
	at com.kotcrab.vis.editor.module.project.ShaderCacheModule$ReloadShaderTask.run(ShaderCacheModule.java:135)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.executeRunnables(LwjglCanvas.java:261)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:227)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: C:\Users\Simon\Downloads\visTest\vis\assets\shader\font (2).frag (The system cannot find the file specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:140)
	... 22 more
```

**Comment by kotcrab** [comment]
Thanks for reporting!
