### ISSUE TITLE
Error loading asset with Artemis-odb 1.1.1

### ISSUE THREAD

**Issue by yichen0831** [kotcrab/VisEditor#55]
EDIT: **Just saw the roadmap of 0.3.0 for Artemis-odb 1.0.1, I guess this issue posted will no longer an issue soon...**

When using with Artemis-odb 0.13.1, VisAssetManager.loadSceneNow() works fine. 

However, after using with Artemis-odb 1.1.1, VisAssetManager.loadSceneNow() throws error:

AssetManager: Error loading asset.
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load asset: scene/main.scene
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:137)
	at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:89)
	at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:479)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:354)
	at com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:377)
	at com.kotcrab.vis.runtime.scene.VisAssetManager.loadSceneNow(VisAssetManager.java:81)
	at com.kotcrab.vis.runtime.scene.VisAssetManager.loadSceneNow(VisAssetManager.java:76)
	at com.viseditortest.VisETest.create(VisETest.java:30)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: java.lang.VerifyError: class com.kotcrab.vis.runtime.system.delegate.DeferredEntityProcessingSystem overrides final method inserted.(I)V
	at com.badlogic.gdx.utils.async.AsyncResult.get(AsyncResult.java:46)
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:135)
	... 9 more
Caused by: java.lang.VerifyError: class com.kotcrab.vis.runtime.system.delegate.DeferredEntityProcessingSystem overrides final method inserted.(I)V
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.kotcrab.vis.runtime.scene.SceneLoader.loadAsync(SceneLoader.java:205)
	at com.kotcrab.vis.runtime.scene.SceneLoader.loadAsync(SceneLoader.java:57)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:73)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:34)
	at com.badlogic.gdx.utils.async.AsyncExecutor$2.call(AsyncExecutor.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: gfx/textures.atlas
	at com.badlogic.gdx.assets.AssetManager.unload(AssetManager.java:182)
	at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:540)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:356)
	at com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:377)
	at com.kotcrab.vis.runtime.scene.VisAssetManager.loadSceneNow(VisAssetManager.java:81)
	at com.kotcrab.vis.runtime.scene.VisAssetManager.loadSceneNow(VisAssetManager.java:76)
	at com.viseditortest.VisETest.create(VisETest.java:30)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by kotcrab** [comment]
Artemis 1.x.x has too many changes compared to 0.13.1. It's impossible to use it with that runtime version. You will have to wait for 0.3.0.

Though, if you really need to use that Artemis version, you could fork runtime and update it on your own so it will use Artemis 1.x.x.
