### ISSUE TITLE
Can't load skin.json

### ISSUE THREAD

**Issue by nchuck** [kotcrab/VisEditor#56]
I receive an Exception when running my project with 0.9.2-SNAPSHOT:

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationException: Error reading file: com/kotcrab/vis/ui/skin/x1/uiskin.json
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:97)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.<init>(Skin.java:74)
	at com.kotcrab.vis.ui.VisUI.load(VisUI.java:90)
	at com.kotcrab.vis.ui.VisUI.load(VisUI.java:84)
	at com.kotcrab.vis.ui.VisUI.load(VisUI.java:77)
	at com.itc.mn.GUI.FrontEnd.<init>(FrontEnd.java:114)
	at com.itc.mn.Pantallas.Pantalla.<init>(Pantalla.java:39)
	at com.itc.mn.Pantallas.RenderScreen.<init>(RenderScreen.java:100)
	at com.itc.mn.Pantallas.SplashScreen.<init>(SplashScreen.java:29)
	at com.itc.mn.MainGame.create(MainGame.java:15)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: com/kotcrab/vis/ui/skin/x1/uiskin.json
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:683)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:95)
	... 11 more
Caused by: com.badlogic.gdx.utils.SerializationException: Field not found: knobOver (com.badlogic.gdx.scenes.scene2d.ui.Slider$SliderStyle)
	at com.badlogic.gdx.utils.Json.readFields(Json.java:776)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:902)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:404)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:834)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.readNamedObjects(Skin.java:425)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:414)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:410)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:867)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:404)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:681)
	... 12 more

If I run it with 0.9.1 it works just fine, but I need the 0.9.2-SNAPSHOT because of the font kerning issues (I'm the guy who posted in kotcrab forums about Me with tildes)

Github proyect (nchuck/MN)

**Comment by kotcrab** [comment]
Looks like you are using libGDX 1.6.5, you need 1.7.0 for VisUI 0.9.2 as described [here](https://github.com/kotcrab/VisEditor/wiki/VisUI#libgdx-compatibility).

**Comment by nchuck** [comment]
Sorry, my bad.
